services:
  - type: web
    name: question-paper-generator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        value: 166839997171300f4a1f899733c043e20d1758d3595ff0c8
      - key: RENDER
        value: "true"
    healthCheckPath: /health
